/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Cover Cache */
        delete: operations["clear_cover_cache_api_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cover/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cover */
        get: operations["get_cover_api_cover__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/llm/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Llm Connection */
        post: operations["test_llm_connection_api_llm_test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/abs/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Abs Connection */
        post: operations["test_abs_connection_api_abs_test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library */
        get: operations["get_library_api_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/in-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get In Progress */
        get: operations["get_in_progress_api_library_in_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library Item */
        get: operations["get_library_item_api_library__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Statistics */
        get: operations["get_statistics_api_statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics/yearly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Yearly Stats */
        get: operations["get_yearly_stats_api_statistics_yearly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics/recap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recap */
        get: operations["get_recap_api_statistics_recap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Heatmap */
        get: operations["get_heatmap_api_statistics_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authors/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Authors */
        get: operations["search_authors_api_authors_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authors/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library Authors */
        get: operations["get_library_authors_api_authors_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Followed Authors */
        get: operations["list_followed_authors_api_authors_get"];
        put?: never;
        /** Follow Author */
        post: operations["follow_author_api_authors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authors/{author_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unfollow Author */
        delete: operations["unfollow_author_api_authors__author_key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Series */
        get: operations["list_series_api_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{series_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Series */
        get: operations["get_series_api_series__series_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases/tracked-authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tracked Authors */
        get: operations["list_tracked_authors_api_releases_tracked_authors_get"];
        put?: never;
        /** Track Author */
        post: operations["track_author_api_releases_tracked_authors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases/tracked-authors/{author_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Untrack Author */
        delete: operations["untrack_author_api_releases_tracked_authors__author_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Releases */
        get: operations["list_releases_api_releases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases/{release_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Release */
        patch: operations["patch_release_api_releases__release_id__patch"];
        trace?: never;
    };
    "/api/releases/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Releases */
        post: operations["refresh_releases_api_releases_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/narrators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Narrators */
        get: operations["list_narrators_api_narrators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/narrators/{narrator_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Narrator */
        get: operations["get_narrator_api_narrators__narrator_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Collections */
        get: operations["list_collections_api_collections_get"];
        put?: never;
        /** Create Collection */
        post: operations["create_collection_api_collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Collection */
        get: operations["get_collection_api_collections__collection_id__get"];
        put?: never;
        post?: never;
        /** Delete Collection */
        delete: operations["delete_collection_api_collections__collection_id__delete"];
        options?: never;
        head?: never;
        /** Patch Collection */
        patch: operations["patch_collection_api_collections__collection_id__patch"];
        trace?: never;
    };
    "/api/collections/{collection_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_api_collections__collection_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{collection_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Item */
        delete: operations["remove_item_api_collections__collection_id__items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Backup */
        get: operations["download_backup_api_backup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Backup */
        post: operations["restore_backup_api_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{abs_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Note */
        get: operations["get_note_api_notes__abs_item_id__get"];
        /** Upsert Note */
        put: operations["upsert_note_api_notes__abs_item_id__put"];
        post?: never;
        /** Delete Note */
        delete: operations["delete_note_api_notes__abs_item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations */
        get: operations["recommendations_api_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_api_recommendations_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations Status */
        get: operations["recommendations_status_api_recommendations_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_api_goals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Goal */
        put: operations["upsert_goal_api_goals__year__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ABSTestRequest */
        ABSTestRequest: {
            /** Url */
            url: string;
            /** Token */
            token: string;
        };
        /** AddItemRequest */
        AddItemRequest: {
            /** Abs Item Id */
            abs_item_id: string;
        };
        /** AuthorCount */
        AuthorCount: {
            /** Name */
            name: string;
            /** Books */
            books: number;
        };
        /** Body_restore_backup_api_restore_post */
        Body_restore_backup_api_restore_post: {
            /** File */
            file: string;
        };
        /** BookProgress */
        BookProgress: {
            /** Is Finished */
            is_finished: boolean;
            /** Progress Pct */
            progress_pct: number;
            /** Current Time */
            current_time: number;
            /** Time Remaining */
            time_remaining: number;
            /** Started At */
            started_at?: number | null;
            /** Finished At */
            finished_at?: number | null;
            /** Last Update */
            last_update?: number | null;
        };
        /** BookSummary */
        BookSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Duration */
            duration: number;
        };
        /** CollectionDetail */
        CollectionDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Created At */
            created_at: string;
            /** Book Count */
            book_count: number;
            /** Item Ids */
            item_ids: string[];
        };
        /** CollectionOut */
        CollectionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Created At */
            created_at: string;
            /** Book Count */
            book_count: number;
        };
        /** CreateCollectionRequest */
        CreateCollectionRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** FollowRequest */
        FollowRequest: {
            /** Name */
            name: string;
            /** Ol Key */
            ol_key?: string | null;
        };
        /** GenreCount */
        GenreCount: {
            /** Name */
            name: string;
            /** Books */
            books: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatmapData */
        HeatmapData: {
            /** Year */
            year: string;
            /** Data */
            data: components["schemas"]["HeatmapPoint"][];
        };
        /** HeatmapPoint */
        HeatmapPoint: {
            /** Date */
            date: string;
            /** Minutes */
            minutes: number;
        };
        /** IngestRequest */
        IngestRequest: {
            /** Isbn */
            isbn?: string | null;
            /** Title */
            title?: string | null;
            /** Author */
            author?: string | null;
            /** Work Key */
            work_key?: string | null;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Book Id */
            book_id: string;
        };
        /** LLMTestRequest */
        LLMTestRequest: {
            /** Endpoint */
            endpoint: string;
            /**
             * Llm Type
             * @default ollama
             */
            llm_type: string;
            /** Api Key */
            api_key?: string | null;
        };
        /** LibraryAuthor */
        LibraryAuthor: {
            /** Name */
            name: string;
            /** Book Count */
            book_count: number;
        };
        /** LibraryBook */
        LibraryBook: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Authors */
            authors: string;
            /** Narrator */
            narrator?: string | null;
            /**
             * Series
             * @default []
             */
            series: components["schemas"]["SeriesEntry"][];
            /** Cover Url */
            cover_url: string;
            /** Duration */
            duration: number;
            /**
             * Genres
             * @default []
             */
            genres: string[];
            /** Description */
            description?: string | null;
            /** Published Year */
            published_year?: string | null;
            /** Isbn */
            isbn?: string | null;
            /** Asin */
            asin?: string | null;
            progress?: components["schemas"]["BookProgress"] | null;
        };
        /** MonthlyPoint */
        MonthlyPoint: {
            /** Month */
            month: string;
            /** Books */
            books: number;
        };
        /** NarratorBook */
        NarratorBook: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Duration */
            duration: number;
            /** Duration Formatted */
            duration_formatted: string;
            /** Is Finished */
            is_finished: boolean;
        };
        /** NarratorDetail */
        NarratorDetail: {
            /** Name */
            name: string;
            /** Book Count */
            book_count: number;
            /** Total Hours */
            total_hours: number;
            /** Finished Count */
            finished_count: number;
            /** Books */
            books: components["schemas"]["NarratorBook"][];
        };
        /** NarratorSummary */
        NarratorSummary: {
            /** Name */
            name: string;
            /** Book Count */
            book_count: number;
            /** Total Hours */
            total_hours: number;
            /** Finished Count */
            finished_count: number;
        };
        /** NoteOut */
        NoteOut: {
            /** Body */
            body: string | null;
        };
        /** NotePut */
        NotePut: {
            /** Body */
            body: string;
        };
        /** OLAuthorResult */
        OLAuthorResult: {
            /** Ol Key */
            ol_key: string;
            /** Name */
            name: string;
            /** Birth Date */
            birth_date?: string | null;
            /** Death Date */
            death_date?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Top Work */
            top_work?: string | null;
            /**
             * Work Count
             * @default 0
             */
            work_count: number;
        };
        /** OverallStats */
        OverallStats: {
            /** Books Completed */
            books_completed: number;
            /** Hours Listened */
            hours_listened: number;
            /** Avg Books Per Month */
            avg_books_per_month: number;
            /** Unique Authors */
            unique_authors: number;
            streak: components["schemas"]["StreakInfo"];
            /** By Year */
            by_year: components["schemas"]["YearlyPoint"][];
        };
        /** PatchCollectionRequest */
        PatchCollectionRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** PatchReleaseRequest */
        PatchReleaseRequest: {
            /** Release Date Confirmed */
            release_date_confirmed?: boolean | null;
            /** Release Date */
            release_date?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ReadDuration */
        ReadDuration: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Days */
            days: number;
        };
        /** ReadingGoalOut */
        ReadingGoalOut: {
            /** Year */
            year: number;
            /** Target Books */
            target_books: number;
        };
        /** ReadingGoalRequest */
        ReadingGoalRequest: {
            /** Target Books */
            target_books: number;
        };
        /** RecapStats */
        RecapStats: {
            /** Year */
            year: string;
            /** Books Finished */
            books_finished: number;
            /** Hours Listened */
            hours_listened: number;
            /** Hours Of Content */
            hours_of_content: number;
            /** Active Months */
            active_months: number;
            /** Top Authors */
            top_authors: components["schemas"]["AuthorCount"][];
            longest_book?: components["schemas"]["BookSummary"] | null;
            shortest_book?: components["schemas"]["BookSummary"] | null;
            fastest_read?: components["schemas"]["ReadDuration"] | null;
            slowest_read?: components["schemas"]["ReadDuration"] | null;
            /** Monthly Pace */
            monthly_pace: components["schemas"]["MonthlyPoint"][];
            /** Top Series */
            top_series: components["schemas"]["GenreCount"][];
        };
        /** RefreshError */
        RefreshError: {
            /** Author */
            author: string;
            /** Message */
            message: string;
        };
        /** RefreshResult */
        RefreshResult: {
            /** Added */
            added: number;
            /** Skipped */
            skipped: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["RefreshError"][];
        };
        /** ReleaseOut */
        ReleaseOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Author Name */
            author_name: string;
            /** Release Date */
            release_date: string | null;
            /** Release Date Confirmed */
            release_date_confirmed: boolean;
            /** Book Number */
            book_number: string | null;
            /** Ol Key */
            ol_key: string | null;
            /** Link Url */
            link_url: string | null;
            /** Notes */
            notes: string | null;
            /** Source */
            source: string | null;
        };
        /** ReleaseTrackedAuthorOut */
        ReleaseTrackedAuthorOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Ol Key */
            ol_key: string | null;
            /** Added At */
            added_at: number;
        };
        /** SeriesBook */
        SeriesBook: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Sequence */
            sequence: string;
            /** Is Finished */
            is_finished: boolean;
            /** Progress */
            progress: number;
            /** Duration */
            duration: number;
            /** Duration Formatted */
            duration_formatted: string;
        };
        /** SeriesDetail */
        SeriesDetail: {
            /** Name */
            name: string;
            /** Author */
            author: string;
            /** Total */
            total: number;
            /** Finished */
            finished: number;
            /** In Progress */
            in_progress: number;
            /** Not Started */
            not_started: number;
            /** Percent Complete */
            percent_complete: number;
            /** Books */
            books: components["schemas"]["SeriesBook"][];
        };
        /** SeriesEntry */
        SeriesEntry: {
            /** Name */
            name: string;
            /** Sequence */
            sequence?: string | null;
        };
        /** SeriesSummary */
        SeriesSummary: {
            /** Name */
            name: string;
            /** Author */
            author: string;
            /** Total */
            total: number;
            /** Finished */
            finished: number;
            /** In Progress */
            in_progress: number;
            /** Not Started */
            not_started: number;
            /** Percent Complete */
            percent_complete: number;
        };
        /** SettingsPatch */
        SettingsPatch: {
            /** Abs Url */
            abs_url?: string | null;
            /** Abs Token */
            abs_token?: string | null;
            /** Recommender Enabled */
            recommender_enabled?: boolean | null;
            /** Recommender Vector Backend */
            recommender_vector_backend?: string | null;
            /** Recommender Embed Model */
            recommender_embed_model?: string | null;
            /** Recommender Top K */
            recommender_top_k?: number | null;
            /** Recommender Min Similarity */
            recommender_min_similarity?: number | null;
            /** Recommender Explanations Enabled */
            recommender_explanations_enabled?: boolean | null;
            /** Llm Type */
            llm_type?: string | null;
            /** Llm Endpoint */
            llm_endpoint?: string | null;
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Api Key */
            llm_api_key?: string | null;
            /** Notifications Enabled */
            notifications_enabled?: boolean | null;
            /** Apprise Url */
            apprise_url?: string | null;
            /** Notify Days Before */
            notify_days_before?: number | null;
            /** Notify Time */
            notify_time?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Releases Refresh Cron */
            releases_refresh_cron?: string | null;
        };
        /** SettingsRead */
        SettingsRead: {
            /** Abs Url */
            abs_url: string | null;
            /** Abs Token */
            abs_token: string | null;
            /** Recommender Enabled */
            recommender_enabled: boolean;
            /** Recommender Vector Backend */
            recommender_vector_backend: string;
            /** Recommender Embed Model */
            recommender_embed_model: string;
            /** Recommender Top K */
            recommender_top_k: number;
            /** Recommender Min Similarity */
            recommender_min_similarity: number;
            /** Recommender Explanations Enabled */
            recommender_explanations_enabled: boolean;
            /** Llm Type */
            llm_type: string;
            /** Llm Endpoint */
            llm_endpoint: string | null;
            /** Llm Model */
            llm_model: string | null;
            /** Llm Api Key */
            llm_api_key: string | null;
            /** Notifications Enabled */
            notifications_enabled: boolean;
            /** Apprise Url */
            apprise_url: string | null;
            /** Notify Days Before */
            notify_days_before: number;
            /** Notify Time */
            notify_time: string;
            /** Timezone */
            timezone: string;
            /** Releases Refresh Cron */
            releases_refresh_cron: string;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Enabled */
            enabled: boolean;
            /** Model */
            model: string | null;
            /** Vector Backend */
            vector_backend: string | null;
        };
        /** StreakInfo */
        StreakInfo: {
            /** Current */
            current: number;
            /** Longest */
            longest: number;
            /** Total Days */
            total_days: number;
        };
        /** TestConnectionResponse */
        TestConnectionResponse: {
            /** Ok */
            ok: boolean;
            /** Models */
            models?: string[] | null;
            /** Error */
            error?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** TrackAuthorRequest */
        TrackAuthorRequest: {
            /** Name */
            name: string;
            /** Ol Key */
            ol_key?: string | null;
        };
        /** TrackedAuthorOut */
        TrackedAuthorOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Ol Key */
            ol_key: string | null;
            /** Photo Url */
            photo_url: string | null;
            /** Bio */
            bio: string | null;
            /** Birth Date */
            birth_date: string | null;
            /** Death Date */
            death_date: string | null;
            /** Followed At */
            followed_at: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** YearlyPoint */
        YearlyPoint: {
            /** Year */
            year: string;
            /** Books */
            books: number;
        };
        /** YearlyStats */
        YearlyStats: {
            /** Year */
            year: string;
            /** Books In Year */
            books_in_year: number;
            /** Monthly Chart */
            monthly_chart: components["schemas"]["MonthlyPoint"][];
            /** Top Authors */
            top_authors: components["schemas"]["AuthorCount"][];
            /** Top Narrators */
            top_narrators: components["schemas"]["AuthorCount"][];
            /** Genre Breakdown */
            genre_breakdown: components["schemas"]["GenreCount"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    clear_cover_cache_api_cache_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_cover_api_cover__item_id__get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
        };
    };
    patch_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_llm_connection_api_llm_test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_abs_connection_api_abs_test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ABSTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_library_api_library_get: {
        parameters: {
            query?: {
                search?: string | null;
                sort?: "title" | "progress_asc" | "progress_desc" | "updated" | "finished";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryBook"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_in_progress_api_library_in_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryBook"][];
                };
            };
        };
    };
    get_library_item_api_library__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryBook"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_statistics_api_statistics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverallStats"];
                };
            };
        };
    };
    get_yearly_stats_api_statistics_yearly_get: {
        parameters: {
            query?: {
                year?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearlyStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recap_api_statistics_recap_get: {
        parameters: {
            query?: {
                year?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecapStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_heatmap_api_statistics_heatmap_get: {
        parameters: {
            query?: {
                year?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_authors_api_authors_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OLAuthorResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_library_authors_api_authors_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryAuthor"][];
                };
            };
        };
    };
    list_followed_authors_api_authors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedAuthorOut"][];
                };
            };
        };
    };
    follow_author_api_authors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedAuthorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unfollow_author_api_authors__author_key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_series_api_series_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesSummary"][];
                };
            };
        };
    };
    get_series_api_series__series_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tracked_authors_api_releases_tracked_authors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseTrackedAuthorOut"][];
                };
            };
        };
    };
    track_author_api_releases_tracked_authors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackAuthorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseTrackedAuthorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    untrack_author_api_releases_tracked_authors__author_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_releases_api_releases_get: {
        parameters: {
            query?: {
                author?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_release_api_releases__release_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                release_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchReleaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_releases_api_releases_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResult"];
                };
            };
        };
    };
    list_narrators_api_narrators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarratorSummary"][];
                };
            };
        };
    };
    get_narrator_api_narrators__narrator_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                narrator_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarratorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collections_api_collections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"][];
                };
            };
        };
    };
    create_collection_api_collections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCollectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_api_collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_collection_api_collections__collection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_collection_api_collections__collection_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchCollectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_item_api_collections__collection_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_item_api_collections__collection_id__items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: number;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_backup_api_backup_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_backup_api_restore_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_restore_backup_api_restore_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_note_api_notes__abs_item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                abs_item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_note_api_notes__abs_item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                abs_item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotePut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_notes__abs_item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                abs_item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_api_recommendations_get: {
        parameters: {
            query?: {
                book_ids?: string | null;
                prompt?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_api_recommendations_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_status_api_recommendations_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    list_goals_api_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingGoalOut"][];
                };
            };
        };
    };
    upsert_goal_api_goals__year__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadingGoalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingGoalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
